@echo off
setlocal

echo ============================================
echo   NetOps Dashboard - Reset to Defaults
echo ============================================
echo.
echo This will:
echo   - Stop the running server
echo   - Delete .env (your settings)
echo   - Delete CLAUDE.md (generated config)
echo.
echo Your code and venv will NOT be touched.
echo.

set /p CONFIRM="Are you sure? (Y/N): "
if /i not "%CONFIRM%"=="Y" (
    echo Cancelled.
    pause
    exit /b 0
)

echo.

:: ---- Kill pythonw.exe first to release file handles ----
taskkill /f /im pythonw.exe >nul 2>&1

:: ---- Also kill by port in case it was launched differently ----
set DASHBOARD_PORT=7000
if exist ".env" (
    for /f "tokens=2 delims==" %%a in ('findstr /b "DASHBOARD_PORT=" .env') do set DASHBOARD_PORT=%%a
)
for /f "tokens=5" %%p in ('netstat -ano -p TCP 2^>nul ^| findstr ":%DASHBOARD_PORT% " ^| findstr "LISTENING"') do (
    if %%p neq 0 (
        echo [..] Stopping server (PID %%p)...
        taskkill /f /t /pid %%p >nul 2>&1
    )
)

:: ---- Wait for processes to fully stop and release file handles ----
timeout /t 3 /nobreak >nul

:: ---- Delete .env ----
if exist ".env" (
    del /f /q ".env"
    if exist ".env" (
        echo [WARN] .env is locked — retrying...
        timeout /t 3 /nobreak >nul
        del /f /q ".env"
    )
    if not exist ".env" (
        echo [OK] Deleted .env
    ) else (
        echo [ERROR] Could not delete .env — it may be locked by another process.
    )
) else (
    echo [--] No .env to delete
)

:: ---- Delete CLAUDE.md (generated by setup wizard) ----
if exist "CLAUDE.md" (
    del /f "CLAUDE.md"
    echo [OK] Deleted CLAUDE.md
) else (
    echo [--] No CLAUDE.md to delete
)

echo.
echo ============================================
echo   Reset complete. Run start.bat to set up
echo   the dashboard again.
echo ============================================
echo.
pause
endlocal
